# Generated by Django 4.0.4 on 2022-05-05 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_followees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followees',
        ),
        migrations.AlterField(
            model_name='user',
            name='introduction',
            field=models.TextField(blank=True, max_length=300, null=True, verbose_name='introduce'),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='ニックネーム'),
        ),
    ]
